name: news_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.3.4
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.6.0
  dio: ^4.0.6
  lottie: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto Slab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
        - asset: assets/fonts/RobotoSlab-Bold.ttf
